/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.sql.*;
import javax.swing.*;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import com.itextpdf.text.BaseColor;
//import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import java.io.IOException;

/**
 * -
 *
 * @author ANTHONY
 */
public class RegistroEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public RegistroEstudiantes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGrado = new javax.swing.JTextField();
        txtSección = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Grado:");

        jLabel3.setText("Sección:");

        btnRegistrar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese el código del alumno:");

        btnBuscar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblEstado.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N

        btnPDF.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnPDF.setText("GENERAR PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnBuscar)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(btnModificar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSección, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGrado, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(175, 175, 175)
                                .addComponent(btnEliminar)))
                        .addGap(18, 18, 18)
                        .addComponent(btnPDF)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSección, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblEstado)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        //Falta validar que el usuario llene todos los datos para poder registrar correctamente        
        try {
            //Realizamos la conexión con la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/practicando", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into estudiantes values(?, ?, ?, ?)");

            //Tenemos que mandar la cantidad de datos necesarios para llenar todos los campos de la tabla
            pst.setInt(1, 0);
            pst.setString(2, txtNombre.getText().trim());
            pst.setString(3, txtGrado.getText().trim());
            pst.setString(4, txtSección.getText().trim());
            pst.executeUpdate(); //Ejecutamos la actualización

            txtNombre.setText("");
            txtGrado.setText("");
            txtSección.setText("");

            lblEstado.setText("REGISTRO EXITOSO");

            cn.close(); //Cerramos la conexión
            pst.close(); //Cerramos el objeto de la consulta

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        //Totalmente validado
        try {
            //Realizamos la conexión a la base de datos
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/practicando", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from estudiantes where ID_Estudiante = (?)");

            //Mandamos a la base de datos el dato que necesita para realizar la búsqueda
            pst.setString(1, txtBuscar.getText().trim());

            //El objeto rs guarda el resultado de la consulta
            ResultSet rs = pst.executeQuery();

            //Si el objeto rs guarda un resultado, la nueva fila actual es válida y devuelve un true
            if (rs.next() == true) {
                txtNombre.setText(rs.getString("NombreEstudiante"));
                txtGrado.setText(rs.getString("Grado"));
                txtSección.setText(rs.getString("Sección"));
                lblEstado.setText("BUSQUEDA EXITOSA");
            } else {
                JOptionPane.showMessageDialog(null, "EL CODIGO NO EXISTE");
            }

            cn.close();
            pst.close();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        //Falta validar que el usuario ingrese un id del estudiante que sea válido para hacer la modificación correctamente
        try {
            String id = txtBuscar.getText().trim();
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/practicando", "root", "");
            PreparedStatement pst = cn.prepareStatement("update estudiantes set NombreEstudiante = ?, Grado = ?, Sección = ? where ID_Estudiante = " + id);

            pst.setString(1, txtNombre.getText().trim());
            pst.setString(2, txtGrado.getText().trim());
            pst.setString(3, txtSección.getText().trim());
            pst.executeUpdate();

            lblEstado.setText("MODIFICACION EXITOSA");

            cn.close();
            pst.close();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        //Falta validar que el usuario ingrese un id del estudiante que sea válido para hacer una eliminación correcta
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/practicando", "root", "");
            PreparedStatement pst = cn.prepareStatement("delete from estudiantes where ID_Estudiante = ?");

            pst.setString(1, txtBuscar.getText().trim());
            pst.executeUpdate();

            txtBuscar.setText("");
            txtNombre.setText("");
            txtGrado.setText("");
            txtSección.setText("");
            lblEstado.setText("ELIMINACION CORRECTA");

            cn.close();
            pst.close();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        try {
            Document documento = new Document();
            PdfWriter.getInstance(documento, new FileOutputStream("C:/Users/ANTHONY/documents/NetBeansProjects/Clase 43/BD_Estudiantes/New PDF/ReporteDatos.pdf"));

            //Colocamos una imagen en el archivo pdf
            Image imagen = Image.getInstance("src/img/hack.png");
            imagen.scaleToFit(1000, 150);
            imagen.setAlignment(Image.ALIGN_CENTER);

            //Insertando texto editado en el archivo pdf
            Paragraph texto1 = new Paragraph();
            Paragraph texto2 = new Paragraph();

            texto1.setAlignment(Paragraph.ALIGN_JUSTIFIED);
            texto1.setFont(FontFactory.getFont("Cambria", 20, Font.BOLD, BaseColor.BLACK));
            texto1.add("\n\n Tabla informativa generada por Gianmarco Contreras \n\n");

            texto2.setAlignment(Paragraph.ALIGN_CENTER);
            texto2.setFont(FontFactory.getFont("Cambria", 20, Font.BOLDITALIC, BaseColor.BLUE));
            texto2.add("\n GCP Copyright ©");

            documento.open();
            documento.add(imagen);
            documento.add(texto1);

            //FileOutputStream: para escribir datos en un archivo
            PdfPTable tabla = new PdfPTable(4);
            tabla.addCell("Código");
            tabla.addCell("Nombre");
            tabla.addCell("Grado");
            tabla.addCell("Sección");

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/practicando", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from estudiantes");
            ResultSet rs = pst.executeQuery();

            if (rs.next() == true) {
                do {
                    tabla.addCell(rs.getString(1));
                    tabla.addCell(rs.getString(2));
                    tabla.addCell(rs.getString(3));
                    tabla.addCell(rs.getString(4));
                } while (rs.next() == true);
            }
            documento.add(tabla);
            documento.add(texto2);
            documento.close();
            cn.close();
            pst.close();
            JOptionPane.showMessageDialog(null, "El reporte fue creado con éxito.");
        } catch (DocumentException | HeadlessException | FileNotFoundException | SQLException e) {

        } catch (IOException e) {

        }
    }//GEN-LAST:event_btnPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtGrado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSección;
    // End of variables declaration//GEN-END:variables
}
